repos:
  # Check YAML; Fix end of files; Fix trailing whitespace
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        name: Check Yaml
      - id: end-of-file-fixer
        name: Fix End of Files
      - id: trailing-whitespace
        name: Fix Trailing Whitespace
  # Python - Reorder Imports
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        name: isort (python)
        args:
          - --force-single-line-imports
          - --lines-after-imports=2
  # Python - Code Formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
        exclude: hooks/.*
      # Run the formatter.
      - id: ruff-format
        exclude: hooks/.*
